<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'knpu_lorem_ipsum.api_controller' shared service.

return $this->services['knpu_lorem_ipsum.api_controller'] = new \KnpU\LoremIpsumIbrahBundle\Controller\IpsumApiController(($this->services['knpu_lorem_ipsum.knpu_ipsum'] ?? $this->load('getKnpuLoremIpsum_KnpuIpsumService.php')));
